# servicios/urls.py
from django.urls import path, include
from servicios import views as servicios_views
from . import views
from django.contrib import admin

app_name = 'servicios'  

urlpatterns = [
    path('servicios/', views.listar_servicios, name='listar_servicios'),
    path('solicitar/', views.solicitar_servicio, name='solicitar_servicio'),
    path('mis-solicitudes/', views.lista_solicitudes, name='lista_solicitudes'),
    path('solicitud/<int:solicitud_id>/', views.detalle_solicitud, name='detalle_solicitud'),
    path('mis-asignaciones/', views.lista_asignaciones, name='lista_asignaciones'),
    path('asignacion/<int:asignacion_id>/', views.detalle_asignacion, name='detalle_asignacion'),
    path('mis-asignaciones/', views.lista_asignaciones, name='lista_asignaciones'),
    path('asignacion/<int:asignacion_id>/', views.detalle_asignacion, name='detalle_asignacion'),
    path('asignacion/<int:asignacion_id>/actualizar-estado/', views.actualizar_estado_servicio, name='actualizar_estado_servicio'),
    path('admin/solicitudes/', views.lista_todas_solicitudes, name='lista_todas_solicitudes'),
    path('admin/solicitud/<int:solicitud_id>/asignar/', views.asignar_tecnico, name='asignar_tecnico'),
    path('admin/solicitud/<int:solicitud_id>/detalle/', views.detalle_solicitud_admin, name='detalle_solicitud_admin'),
    path('admin/tipos-servicio/', views.lista_tipos_servicio, name='lista_tipos_servicio'),
    path('admin/tipos-servicio/crear/', views.crear_tipo_servicio, name='crear_tipo_servicio'),
    path('admin/tipos-servicio/editar/<int:tipo_id>/', views.editar_tipo_servicio, name='editar_tipo_servicio'),
    path('admin/tipos-servicio/eliminar/<int:tipo_id>/', views.eliminar_tipo_servicio, name='eliminar_tipo_servicio'),
    path('solicitud/<int:solicitud_id>/calificar/', views.calificar_servicio, name='calificar_servicio'),
    path('historial/', views.historial_servicios, name='historial_servicios'),
    path('notificaciones/', views.lista_notificaciones, name='lista_notificaciones'),
    path('notificaciones/leida/<int:notificacion_id>/', views.marcar_leida, name='marcar_leida'),
    path('tecnico/perfil/', views.ver_perfil_tecnico, name='ver_perfil_tecnico'),
    path('tecnico/perfil/editar/', views.editar_perfil_tecnico, name='editar_perfil_tecnico'),
    path('admin/tecnicos/', views.lista_tecnicos, name='lista_tecnicos'),
    path('admin/solicitudes/', views.lista_solicitudes_admin, name='lista_solicitudes_admin'),
    path('admin/tipos/', views.gestion_tipos_servicio, name='gestion_tipos_servicio'),
    path('', views.pagina_principal, name='pagina_principal'),
    path('', servicios_views.pagina_principal, name='pagina_principal'),
    path('admin/', admin.site.urls),
    path('admin/tecnicos/', views.lista_tecnicos, name='lista_tecnicos'),
    path('admin/tecnicos/<int:tecnico_id>/', views.detalle_tecnico, name='detalle_tecnico'),
    path('admin/usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('admin/usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('admin/usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('admin/usuarios/crear/tecnico/', views.crear_tecnico, name='crear_tecnico'),
    path('admin/tecnicos/<int:tecnico_id>/', views.detalle_tecnico, name='detalle_tecnico'),
    path('admin/usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('admin/usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('admin/usuarios/crear/tecnico/', views.crear_tecnico, name='crear_tecnico'),
    path('admin/usuarios/editar/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('admin/usuarios/editar/tecnico/<int:usuario_id>/', views.editar_tecnico, name='editar_tecnico'),
    path('admin/tecnicos/<int:tecnico_id>/', views.detalle_tecnico, name='detalle_tecnico'),
    path('admin/usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('admin/usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('admin/usuarios/crear/tecnico/', views.crear_tecnico, name='crear_tecnico'),
    path('admin/usuarios/editar/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('admin/usuarios/editar/tecnico/<int:usuario_id>/', views.editar_tecnico, name='editar_tecnico'),
    path('admin/usuarios/eliminar/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('admin/grupos/', views.lista_grupos, name='lista_grupos'),
    path('admin/grupos/crear/', views.crear_grupo, name='crear_grupo'),
    path('admin/grupos/editar/<int:grupo_id>/', views.editar_grupo, name='editar_grupo'),
    path('admin/grupos/eliminar/<int:grupo_id>/', views.eliminar_grupo, name='eliminar_grupo'),
    path('admin/tecnicos/<int:tecnico_id>/', views.detalle_tecnico, name='detalle_tecnico'),
    path('servicios/', views.listar_servicios, name='listar_servicios'),
    path('solicitar-servicio/', views.solicitar_servicio, name='solicitar_servicio'),
    path('solicitar/', views.solicitar_servicio, name='solicitar_servicio'),
    path('solicitar/plomeria/', views.solicitar_plomeria, name='solicitar_plomeria'),
    path('solicitar/electricista/', views.solicitar_electricista, name='solicitar_electricista'),
    path('solicitar/limpieza/', views.solicitar_limpieza, name='solicitar_limpieza'),
    path('servicios/', views.lista_servicios, name='lista_servicios'),
    path('servicios/', views.lista_servicios, name='lista_servicios'),
    path('servicios/', views.ServicioList.as_view(), name='lista_servicios'),
    path('solicitudes/', views.SolicitudServicioCreate.as_view(), name='crear_solicitud'),
    path('solicitar/', views.solicitar_servicio, name='solicitar_servicio'),
    path('solicitudes/<int:pk>/', views.SolicitudServicioDetail.as_view(), name='detalle_solicitud'), 
]